#pragma once
#define DEBUG
//#define DOPRINT

#define LOAD_INIT_STATE true

#define DRONE_NO_MORE_ICEBERGS UINT_MAX
#define DRONE_SHORTEST_PATH 1
#define DRONE_PRIORITY_SCALER 30.0
#define DRONE_MOVEMENT_SPEED 5 //x,y coordinate per timestep
#define DRONE_FOW 11
#define COM_NODE_SLACK (DRONE_MOVEMENT_SPEED+2)

#define TOLATE_PENALTY 0.2
#define MAX_NUMBER_ITTERATIONS 12

#define NUMBER_LIMITED_DRONES 0

#define MAX_ICEBERG_DISTANCE 1000
#define MIN_ICEBERG_DISTANCE 50

#define ICEBERGDATA_NO_OWNER  -1
#define ICEBERGDATA_DISTANCE_SCALER 1

#define NUMBER_OF_DRONES 10
#define NUMBER_OF_ICEBERGS 60
#define COMMUNICATION_RADIUS 200
#define PLANNED_COMMUNICATION_RADIUS (COMMUNICATION_RADIUS-10)
#define INCREMENT_TIME_COUNTDOWN_MAX 4

#define INITIAL_DRONE_SPREAD 10

#define BOARD_SIZE_X 1000
#define BOARD_SIZE_Y 1000
#define BOARD_MIN_X 0
#define BOARD_MIN_Y 0

#define PATH_NO_ICEBERG -1 
#define NO_OWNER -1

#define MAX_TIME 6000

#define TIMEOUTMAX 10